### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by rbsec** [rbsec/sslscan#185]
Various things to look at/fix/test for the new version of sslscan (#175)

- [ ] Ciphersuite/DHE/curve colouring
- [x] XML output
- [ ] Readme
- [ ] Makefile (decide about static make, warnings, etc)
- [ ] Debian build script
- [ ] zsh completion
- [x] Colouring for TLSv1.3 enabled
- [x] Padding for SSL/TLS versions enabled
- [x] Modify docker_test.sh
  - [x] Work on non-Debian systems
  - [x] Shallow clone OpenSSL repo
  - [x] Support systems with IPv6 (::1 rather than 127.0.0.1 - add `--ipv4` to options)

**Comment by jtesta** [comment]
> Work on non-Debian systems

What OS do you use?  I can add support for it.

> Shallow clone OpenSSL repo

I'm not familiar with shallow cloning.  If you can describe what to change, though, I can add it.

> Support systems with IPv6

You mean you'd like to test that sslscan can connect to the docker instance with IPv6?  I could do that as well.

If there's anything you could use help with in order to get the merge & beta release done, please let me know!

**Comment by rbsec** [comment]
> > Work on non-Debian systems
> 
> What OS do you use? I can add support for it.

I use Arch - the main script itself works fine, it just fails on the [dependency check](https://github.com/jtesta/sslscan/blob/tls_v13/docker_test.sh#L490) because dpkg doesn't exist. Rather than trying to support all the different package managers (or trying to work out if the library is installed without them), it's probably easiest just to only run that check if `dpkg` exists.

> > Shallow clone OpenSSL repo
> 
> I'm not familiar with shallow cloning. If you can describe what to change, though, I can add it.

Shallow cloning means you can only check out the latest X commits, so if you do `git clone --depth 1 https://github....` it only pulls down the HEAD, which is faster. You don't have any of the history - but we don't need that.

> > Support systems with IPv6
> 
> You mean you'd like to test that sslscan can connect to the docker instance with IPv6? I could do that as well.

If your system has IPv6 configured then `localhost` will sometimes (always?) resolve to `::1` rather than `127.0.0.1` - so all the checks fail because the output doesn't match.

```
--- docker_test/expected_output/test_1.txt      2019-12-26 11:05:22.459999441 +0000
+++ /tmp/sslscan_test-results_doVZhkz9RU/test_1.txt     2020-01-14 20:10:40.717356103 +0000
@@ -1,5 +1,5 @@

-Connected to 127.0.0.1
+Connected to ::1
```

Could be fixed either by telling sslscan to scan `127.0.0.1` rather than `localhost`, or by passing the `--ipv4` flag.

> If there's anything you could use help with in order to get the merge & beta release done, please let me know!

To be completely honest I've not really touched sslscan in the last week or so - I'm afraid various other things have been taking up most of my time. Unless you're working on anything at the moment, I think I'll merge your PR into the sslscan2 branch and then we can just PR more stuff into that as needed. Hopefully might get some beta testers for it as well.

Thanks again for all your work on this.

**Comment by jtesta** [comment]
> I use Arch

Fixed.

> Shallow cloning means you can only check out the latest X commits

Ahh, gotcha.  Done.

> Support systems with IPv6 [...] Could be fixed either by telling sslscan to scan 127.0.0.1 rather than localhost

Fixed as well.  Tests are now explicitly run again 127.0.0.1.

> Unless you're working on anything at the moment, I think I'll merge your PR into the sslscan2 branch and then we can just PR more stuff into that as needed.

Sure, that works for me!

> Thanks again for all your work on this.

No problem!

**Comment by rbsec** [comment]
Fantastic - I've merge it into the sslscan2 branch and updated the README with some notes. I'll try and go through some of the points above as and when I have time, then we can look to merge into master.

**Comment by jtesta** [comment]
If you could elaborate on any of the remaining tasks and make a list of concrete goals, I can lend a hand.  I'd love to see a release of the new code, especially with the new LTS version of Ubuntu server coming out in April (which I assume will come with TLSv1.3 enabled by default in nginx/Apache).

Just let me know how I can help!

**Comment by rbsec** [comment]
Once again I'm afraid that many other things have pushed this down my list - apologies. I've been having a little play this evening and made some fairly small changes (mostly output related) as well as merging in a PR that fixed a bug in the XML output.

I've just been playing with static vs dynamic builds - the only thing that really seems to be broken in the dynamic build is compression support (which pretty much every distro will have dropped by now). I wonder if it's worth trying to get that check without needing OpenSSL to support it - that would mean that the vast majority of people won't need to statically build, which should also mean that distros shipping it will probably be shipping a useful version.

I think the only other thing I'd want before pushing this into master would be to consider whether we want to do any colouring for the key exchange groups/signature algorithms and the TLSv1.3 ciphers. Need to have a big more of a read into those to see if there are any particular ones we should be flagging as good or bad.

Thanks once again for all your help with this.

**Comment by jtesta** [comment]
Regarding the compression support: that's something that can (eventually) be done with a ClientHello/ServerHello test.  Its not a huge job, but its big enough that I shouldn't commit to working on it at this time; I'm juggling too many other things at the moment.  But perhaps in a couple weeks I'll be able to return to it.

In the meantime, we could just drop the OpenSSL compression test and open an issue to track it.  Releasing a beta version or two without it should be fine.  Then before launching the stable version, we can get it back in.  Just a thought.

**Comment by rbsec** [comment]
@jtesta the compression can certainly wait - it works at the moment with a static build and warns you if it's nor supported - so I don't think there's any issue leaving it as-is for now. It's pretty rare to see anyway (as it's been disabled for years, and I don't think Microsoft ever supported it). I've made an issue for it (#192 ) to track it anyway.

I've merged  the latest code (with various little fixes an updates) into master and tagged it as 2.0.0-alpha1 - so hopefully some people will start using it and we'll get some feedback.

Thanks once again for all your work with this.

**Comment by jtesta** [comment]
Great!

Would you also be able to include a Windows build?  That way people can get started testing that as well.

**Comment by rbsec** [comment]
@jtesta after some faffing around with MinGW I've uploaded a Windows build. Tested it in Wine and it seems to work, although could probably do with some proper testing in Windows.

**Comment by jtesta** [comment]
I tested the Windows build on Windows 10, and it seems to be working as expected.  I found a couple minor imperfections in the output though:

```
C:\Users\testuser\Desktop>sslscan.exe
[...]
                2.0.0 Windows 64-bit (Mingw)
                OpenSSL 1.1.1e-dev  xx XXX xxxx
OpenSSL version does not support SSLv2
SSLv2 ciphers will not be detected
```

Tthe "xx XXX xxxx" is not filled in.  It also complains about this version of OpenSSL not supporting SSLv2, which doesn't matter.

Not a huge deal, but it would look nicer if polished.  Perhaps I'll send a PR for it in a few days...

**Comment by rbsec** [comment]
The SSLv2 should be fixed by #195 (which has been merged). Not sure about the `xx XXX xx` versioning - but it's a fairly minor UI thing, so can go onto the list of things to look into at some point..

**Comment by jtesta** [comment]
> especially with the new LTS version of Ubuntu server coming out in April (which I assume will come with TLSv1.3 enabled by default in nginx/Apache).

FYI: Ubuntu 20.04 LTS just came out today, and I can confirm that TLSv1.3 is enabled by default in the nginx config.  So I'd expect to see much faster adoption of v1.3 over the next 12 months!

The bad news is TLSv1.0 is also enabled by default.  :(

**Comment by rbsec** [comment]
It'll be interesting to see how much that affects the adoption of TLSv1.3. It's a little frustrating that big providers like AWS still haven't implemented it.

Not really sure why they're keeping TLSv1.0 (given no major browsers support it). Especially frustrating that it's in an LTS version, because it means that it'll be enabled by default for the next 5 years...
